### ISSUE TITLE
[Logger] Format log file in columns

### ISSUE THREAD

**Issue by fin-ger** [fin-ger/FreezingArcher#3]
Add an option to format the log file in columns. Currently the log file is hard to read as not all log-levels, module-names, timestamps, etc. are arranged in one column ("not aligned").

Example:
change

    [Debug] 05.03.2015 01:08:46 [ConfigManager]: Initializing config manager ...
    [Info] 05.03.2015 01:08:46 [ConfigFile_freezing_archer]: Reading freezing_archer.conf
    [Debug] 05.03.2015 01:08:47 [ConfigManager]: Adding freezing_archer.conf to config manager ...
    [Debug] 05.03.2015 01:08:47 [ConfigFile_freezing_archer]: Getting value 'general:resolution' from freezing_archer.conf ...
    [Debug] 05.03.2015 01:08:47 [ConfigFile_freezing_archer]: Getting value 'general:fullscreen_resolution' from freezing_archer.conf ...
    [Debug] 05.03.2015 01:08:47 [Window_FreezingArcher]: Creating new window 'FreezingArcher'
    [Debug] 05.03.2015 01:08:47 [MessageManager]: Creating new message manager

to

    [Debug] 05.03.2015 01:08:46 [      ConfigManager       ]: Initializing config manager ...
    [Info ] 05.03.2015 01:08:46 [ConfigFile_freezing_archer]: Reading freezing_archer.conf
    [Debug] 05.03.2015 01:08:47 [      ConfigManager       ]: Adding freezing_archer.conf to config manager ...
    [Debug] 05.03.2015 01:08:47 [ConfigFile_freezing_archer]: Getting value 'general:resolution' from freezing_archer.conf ...
    [Debug] 05.03.2015 01:08:47 [ConfigFile_freezing_archer]: Getting value 'general:fullscreen_resolution' from freezing_archer.conf ...
    [Debug] 05.03.2015 01:08:47 [  Window_FreezingArcher   ]: Creating new window 'FreezingArcher'
    [Debug] 05.03.2015 01:08:47 [      MessageManager      ]: Creating new message manager

**Comment by martin31821** [comment]
fixed in f2ae655
