### ISSUE TITLE
[Logger] Different command line output than log file content

### ISSUE THREAD

**Issue by fin-ger** [fin-ger/FreezingArcher#5]
Make the command line output different from what is written to the log file.

Example:
logfile

    [Info] 05.03.2015 01:08:46 [Log-System]: Logfile opened.
    [Info] 05.03.2015 01:08:46 [Log-System]: Debugger attached, using DebugWriter
    [Debug] 05.03.2015 01:08:46 [Application_FreezingArcher]: Creating new application 'FreezingArcher'
    [Debug] 05.03.2015 01:08:46 [ConfigManager]: Loading configuration defaults ...
    [Debug] 05.03.2015 01:08:46 [ConfigManager]: Initializing config manager ...

command line

    * [Log-System] Logfile opened.
    * [Log-System] Debugger attached, using DebugWriter
    * [Application_FreezingArcher] Creating new application 'FreezingArcher'
    * [ConfigManager] Loading configuration defaults ...
    * [ConfigManager] Initializing config manager ...

Colourize the `*` regarding to its log level. This behaviour is similar to gentoo portage.

**Comment by martin31821** [comment]
wontfix
