### ISSUE TITLE
[Sound] Add a sound interface

### ISSUE THREAD

**Issue by fin-ger** [fin-ger/FreezingArcher#9]
Please add some ideas what features the sound interface should have.

**Comment by martin31821** [comment]
+ basically play sound x at position y with sound settings z
+ Sound engine should communicate via messagemanager
+ Support for sound groups
 + Music
 + Effects
 + Voice
+ Sound engine should take care of user settings for gain etc.
+ Multiple sounds played parallel
+ Digital Signal Processing, such as LowPass, HighPass, Delay, Reverb
+ Sound Formats:
 + Wave
 + vorbis
 + mp3/aac (optional)

**Comment by martin31821** [comment]
was implemented using OpenAL soft v.1.15+
tested using Linux and Windows
see branch sound for implementation details
